# Generated by Django 2.2.1 on 2020-02-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=50, verbose_name='出版社地址')),
            ],
            options={
                'db_table': 'publish',
                'verbose_name_plural': '出版社',
            },
        ),
    ]
